drop table if exists bookmarks;

create table bookmarks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT NOT NULL,
    rating NUMERIC
);

insert into bookmarks
(title, url, description, rating)
values
('Thinkful', 'https://www.thinkful.com', 'Think outside the classroom', 5),
('Google', 'https://www.google.com', 'Where we find everything else', 4),
('MDN', 'https://developer.mozilla.org', 'The only place to find web documentation', 5)
limit 10;